spring:

  # 데이터 소스 설정
  datasource:
    url: "your database url"
    #    url: jdbc:mariadb://localhost:3306/42gg2
    driverClassName: "your driver class name"
    username: "your database username"
    password: "your database password"

  # JPA 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: false